import { ThemeColors } from '@/types/theme.types';

export const DEFAULT_THEME: ThemeColors = {
  // Top Bar - Soft dark gray
  TOP_BAR_BG_COLOR: '#FFFFFF',
  TOP_BAR_FORE_COLOR: '#000000',

  // Category Bar - Medium gray with subtle hover/active states
  CATEGORY_BAR_BG_COLOR: '#E5E7EB',
  CATEGORY_BAR_FORE_COLOR: '#1F2937',
  CATEGORY_HOVER_COLOR: '#FFFFFF',
  CATEGORY_ACTIVE_COLOR: '#9CA3AF',

  // Product - Clean white/gray
  PRODUCT_BG_COLOR: '#FFFFFF',
  PRODUCT_NAME_FORE_COLOR: '#111827',
  PRODUCT_DESC_FORE_COLOR: '#99a1af',
  PRODUCT_HOVER_COLOR: '#FFFFFF',
  PRODUCT_PRICE_BG_COLOR: '#FFFFFF',
  PRODUCT_PRICE_FORE_COLOR: '#101828',
  PRODUCT_ADD_BTN_BG_COLOR: '#6B7280',

  // Footer - Dark gray
  FOOTER_BG_COLOR: '#1F2937',
  FOOTER_FORE_COLOR: '#F9FAFB',

  // Cart - Medium gray
  VIEW_CART_BG_COLOR: '#4B5563',
  VIEW_CART_FORE_COLOR: '#FFFFFF',

  // Product Popup - Light and neutral
  PRODUCT_POPUP_BG_COLOR: '#FFFFFF',
  PRODUCT_POPUP_HEADER_BG_COLOR: '#FFFFFF',
  PRODUCT_POPUP_HEADER_FORE_COLOR: '#111827',
  PRODUCT_POPUP_DESC_FORE_COLOR: '#99a1af',
  PRODUCT_POPUP_PRICE_FORE_COLOR: '#1F2937',
  PRODUCT_POPUP_ADD_TO_CART_FORE_COLOR: '#FFFFFF',
  PRODUCT_POPUP_ADD_TO_CART_BG_COLOR: '#4B5563',
  PRODUCT_POPUP_PLUS_MINUS_BG_COLOR: '#6B7280',
  PRODUCT_POPUP_QTY_FORE_COLOR: '#111827',

  // Deal Popup - Neutral text
  DEAL_POPUP_OPTION_NAME_FORE_COLOR: '#374151',
  DEAL_POPUP_PRODUCT_NAME_FORE_COLOR: '#1F2937',

  // Core - Neutral gray as primary
  PRIMARY_COLOR: '#6B7280',
  SECONDARY_COLOR: '#FFFFFF',
  WEB_BG_COLOR: '#F9FAFB',
};