import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner"
import Footer1 from "@/components/shared/footer";
import Header1 from "@/components/shared/headers";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/contexts/ThemeProvider";
import { CartDrawer } from "@/components/shared/cart/CartDrawer";
import { ProductModal } from "@/components/menu/partials/product-modal/ProductModal";
import { AddressSelectionModal } from "@/components/address-modal/AddressSelectionModal";
import { SignalRProvider } from "@/contexts/signalr-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Web Ordering",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ThemeProvider>
            <SignalRProvider>
              <Header1 />
              {children}
              <Toaster position="top-center" richColors />
              <AddressSelectionModal />
              <ProductModal />
              <CartDrawer />
              <Footer1 />
            </SignalRProvider>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
