import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import Header1 from "@/components/shared/headers";
import Footer1 from "@/components/shared/footer";
import { Geist, Geist_Mono } from "next/font/google";
import { MenuProvider } from "@/contexts/MenuContext"
import { ProductModal } from "@/components/menu/partials/product-modal/ProductModal";
import { Toaster } from "@/components/ui/sonner"
import { CartDrawer } from "@/components/shared/cart/CartDrawer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Web Ordering",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <MenuProvider>
            <Header1 />
            {children}
            <Toaster position="top-center"/>
            <ProductModal/>
            <CartDrawer />
            <Footer1 />
          </MenuProvider>
        </Providers>
      </body>
    </html>
  );
}
