import "../globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner"
import Footer1 from "@/components/shared/footer";
import Header1 from "@/components/shared/headers";
import { Geist, Geist_Mono } from "next/font/google";
import { CartDrawer } from "@/components/shared/cart/CartDrawer";
import { ProductModal } from "@/components/menu/partials/product-modal/ProductModal";
import { AddressSelectionModal } from "@/components/address-modal/AddressSelectionModal";
import { SignalRProvider } from "@/contexts/signalr-provider";
import { SearchProvider } from "@/contexts/SearchContext";
import { ThemeProvider } from "@/contexts/ThemeProvider";

import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { routing } from '@/i18n/routing';
import React from "react";
import { BranchStatus } from "@/components/shared/BranchStatus";

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Web Ordering",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {

  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  // if (!routing.locales.includes(locale as typeof routing.locales[number])) {
  //   notFound();
  // }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale === 'ur' || locale === 'ur' ? 'rtl' : 'ltr'}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <NextIntlClientProvider messages={messages}>
            <SearchProvider>
              <SignalRProvider>
                <ThemeProvider>
                  <BranchStatus />
                  <Header1 />
                  {children}
                  <Toaster position="top-center" richColors />
                  <AddressSelectionModal />
                  <ProductModal />
                  <CartDrawer />
                  <Footer1 />
                </ThemeProvider>
              </SignalRProvider>
            </SearchProvider>
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}
